name: dart_ewelink_api_example
description: Usage example of dart_ewelink_api
version: 0.0.1
homepage: https://github.com/ianmaciel/dart_ewelink_api
publish_to: none


environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dart_ewelink_api:
    path: ../
